_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "weights/pretrain_weights/ImageNetPretrained/MSRA/R-101.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  RPN:
    PRE_NMS_TOPK_TEST: 6000
    POST_NMS_TOPK_TEST: 1000
  ROI_HEADS:
    NUM_CLASSES: 60
DATASETS:
  TRAIN: ('coco14_trainval_base',)
  TEST: ('coco14_test_base',)
SOLVER:
  IMS_PER_BATCH: 16
  STEPS: (80000, 100000)
  MAX_ITER: 110000
  CHECKPOINT_PERIOD: 10000
OUTPUT_DIR: "/Path/to/Output/Dir"