_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "weights/pretrain_weights/ImageNetPretrained/MSRA/R-101.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  BACKBONE:
    FREEZE: True
  RPN:
    PRE_NMS_TOPK_TEST: 6000
    POST_NMS_TOPK_TEST: 1000
  ROI_HEADS:
    NUM_CLASSES: 60
DATASETS:
  TRAIN: ('coco14_trainval_base',)
  TEST: ('coco14_test_base',)
SOLVER:
  IMS_PER_BATCH: 14
  BASE_LR: 0.01
  STEPS: (8000, 9000)
  MAX_ITER: 10000
  CHECKPOINT_PERIOD: 100000
OUTPUT_DIR: "/Path/to/Output/Dir"