_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "/Path/to/Base/Pretrain/Weight"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  BACKBONE:
    FREEZE: True
  PROPOSAL_GENERATOR:
    FREEZE: False
  ROI_HEADS:
    NUM_CLASSES: 20
    POSITIVE_FRACTION: 0.5
DATASETS:
  TRAIN: ("coco14_trainval_novel_1shot_seed0", )
  TEST: ('coco14_test_novel',)
SOLVER:
  IMS_PER_BATCH: 14
  BASE_LR: 0.01
  STEPS: (800,)
  MAX_ITER: 1000
  CHECKPOINT_PERIOD: 100000
  WARMUP_ITERS: 0
OUTPUT_DIR: "/Path/to/Output/Dir"
MEGA:
  ENTROPY_LOSS_WEIGHTS: 0.0
  REP_LOSS_WEIGHTS: 100.0