_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "/Path/to/Base/Pretrain/Weight"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NUM_CLASSES: 20
DATASETS:
  TRAIN: ('coco14_trainval_novel_10shot_seedx',)
  TEST: ('coco14_test_novel',)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.01
  STEPS: (2000,)
  MAX_ITER: 2500
  CHECKPOINT_PERIOD: 100000
  WARMUP_ITERS: 0
OUTPUT_DIR: "/Path/to/Output/Dir"