_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "/Path/to/Base/Pretrain/Weight"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  BACKBONE:
    FREEZE: False
  ROI_HEADS:
    NUM_CLASSES: 60
DATASETS:
  TRAIN: ("coco14_trainval_base_1shot_seed0", )
  TEST: ('coco14_test_base',)
SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.01
  STEPS: (80000,)
  MAX_ITER: 100000
  CHECKPOINT_PERIOD: 100000
  WARMUP_ITERS: 0
OUTPUT_DIR: "/Path/to/Output/Dir"