_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "/Path/to/Base/Pretrain/Weight"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  BACKBONE:
    FREEZE: False
  ROI_HEADS:
    NUM_CLASSES: 20
  # ROI_BOX_HEAD:
  #   CONTRASTIVE_BRANCH:
  #     TEMPERATURE: 0.2
  #     LOSS_WEIGHT: 0.2
  #     DECAY:
  #       ENABLED: True
  #       STEPS: [3000, 6000]
  #       RATE: 0.5
  #     IOU_THRESHOLD: 0.6

DATASETS:
  TRAIN: ('coco14_trainval_novel_1shot_seedx',)
  TEST: ('coco14_test_novel',)
SOLVER:
  IMS_PER_BATCH: 14
  BASE_LR: 0.01
  STEPS: (600,)
  MAX_ITER: 800
  CHECKPOINT_PERIOD: 100000
  WARMUP_ITERS: 100
OUTPUT_DIR: "/Path/to/Output/Dir"
# MEGA:
#   ENTROPY_LOSS_WEIGHTS: 0.0
#   REP_LOSS_WEIGHTS: 100.0