_BASE_: "../../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "weights/pretrain_weights/ImageNetPretrained/MSRA/R-101.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  BACKBONE:
    FREEZE: True
  RPN:
    PRE_NMS_TOPK_TEST: 6000
    POST_NMS_TOPK_TEST: 1000
  ROI_HEADS:
    NUM_CLASSES: 60
  ROI_BOX_HEAD:
    CONTRASTIVE_BRANCH:
      TEMPERATURE: 0.2
      LOSS_WEIGHT: 0.2
      DECAY:
        ENABLED: True
        STEPS: [10000, 12000]
        RATE: 0.5
      IOU_THRESHOLD: 0.6 

DATASETS:
  TRAIN: ('coco14_trainval_base',)
  TEST: ('coco14_test_base',)
SOLVER:
  IMS_PER_BATCH: 14
  BASE_LR: 0.01
  STEPS: (10000, 12000)
  MAX_ITER: 15000
  CHECKPOINT_PERIOD: 100000
OUTPUT_DIR: "/Path/to/Output/Dir"
MEGA:
  ENTROPY_LOSS_WEIGHTS: 0.0
  REP_LOSS_WEIGHTS: 1.0
  RPN_LEARNER_DIM: 512
  ROIHEADS_LEARNER_DIM: 512